# Generated by Django 4.2.3 on 2023-07-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='freeDelivery',
            new_name='free_delivery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fullDescription',
            new_name='full_description',
        ),
    ]
