version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: topstoredock
      POSTGRES_USER: admin_topstore
      POSTGRES_PASSWORD: 123123
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    restart: always

  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command:
      - gunicorn
      - topstore.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    restart: always
    build:
      dockerfile: ./Dockerfile
    command:
      - celery
      - -A
      - topstore
      - worker
      - --loglevel=info

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ['/wait-for-it.sh']

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/vol/staticfiles
      - media_volume:/vol/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_volume:
  media_volume: