# Generated by Django 4.2.3 on 2023-07-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentType',
            new_name='payment_type',
        ),
    ]
